add entrypoints burning most steps
walnuthq/starkflare-indexer pull request #5
Opened 2024-05-30 15:13 UTC by saimeunt

This PR introduces a new PL/PGSQL function `get_entrypoints(varchar(66))` to fetch entrypoints from a given contract address.

It returns a top level JSON object having a unique `entrypoints` member which is an array of entrypoints identified by their selector as well as the number of steps used and the percentage of steps used compared to other entrypoints in the contract.

2024-05-31 19:55 UTC, jaipaljadeja commented
LGTM!

2024-05-31 20:55 UTC, jaipaljadeja approved these changes

2024-06-03 20:12 UTC, barabanovro requested changes
Please rename the migration file to 007_get_entrypoints.up.sql

2024-06-04 10:09 UTC, saimeunt commented
@barabanovro The migration file has been renamed accordingly 👌

2024-06-04 12:43 UTC, barabanovro approved these changes

2024-06-04 12:43 UTC, merged